### ISSUE TITLE
欢迎dpdk开发爱好者一起合作

### ISSUE THREAD

**Issue by Mark3un** [GumpSun/dpdkPacketgen#1]
@1amfine2333 感谢兄台关注该项目，从事什么方向开发呢，感兴趣的话一起合作哟~

**Comment by Mark3un** [comment]
@anrongwn 感谢兄台关注该项目，从事什么方向开发呢，感兴趣的话一起合作哟~

**Comment by Mark3un** [comment]
@lzqyrgithub 感谢兄台关注该项目，从事什么方向开发呢，感兴趣的话一起合作哟~

**Comment by junjiezou1** [comment]
哈哈哈，大佬您好，不知道你是否介意加一下我的微信呢？我目前也在从事这个方面，希望和你讨论一下。（微信：13933658757）
